version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:1.6.12
    container_name: mosquitto
    ports:
      - '1883:1883'
    networks:
      - development

  postgres:
    image: postgres:11.4
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: dev_pass
      POSTGRES_USER: dev
      POSTGRES_DB: water_db
    ports:
      - 5432:5432
    networks:
      - development

networks:
  development:
    driver: bridge
